openapi: 3.0.0
info:
  title: Generic Component API
  version: 1.0.0

paths:
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Component is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy