openapi: 3.0.0
info:
  title: Component API Placeholder
  version: 1.0.0
  description: This file is a placeholder. Refer to other component-specific YAML files for actual API definitions.
paths:
  /:
    get:
      summary: Placeholder endpoint
      description: This endpoint is a placeholder.
      responses:
        '200':
          description: Successful response (placeholder)